name: clipsesh

services:
  mongo:
    image: mongo:latest
    container_name: clipsesh-mongo
    ports:
      - "27017:27017"
    volumes:
        - mongo-data:/data/db
        - type: bind
          source: ./mongo
          target: /dump

  api:
    build:
      context: ./backend
    container_name: clipsesh-api
    ports:
      - "86:80"
    volumes:
      - type: bind
        source: ./backend/src/uploads
        target: /var/www/backend/src/uploads
      - type: bind
        source: ./backend/src/profilePictures
        target: /var/www/backend/src/profilePictures
      - type: bind
        source: ./backend/src/download
        target: /var/www/backend/src/download
      - type: bind
        source: ./backend/src/scripts
        target: /var/www/backend/src/scripts
      - type: bind
        source: ./backend/src/download/tmp
        target: /var/www/backend/src/download/tmp
    depends_on:
      - mongo
    environment:
      - VIRTUAL_HOST=api.spoekle.com
      - MONGO_URI=mongodb://mongo:27017/clipsDB

  frontend:
    build:
      context: ./frontend
    container_name: clipsesh-frontend
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=clipsesh.spoekle.com

  discord-bot:
    image: clipsesh-discord-bot
    build:
      context: ./discord-bot
      cache_from:
        - clipsesh-discord-bot:latest
    container_name: clipsesh-discord-bot
    volumes:
      - ./discord-bot/logs:/app/logs
    restart: unless-stopped
    depends_on:
      - api

volumes:
  mongo-data:
